In [1]:
# Light-GG
# Memory saving algorithm to create a coordinate system (2D), but with human-intuitive inputs

In [23]:
#import the necessary packages

#for working with array data
import numpy as np

# for astronomy considerations
from astropy import units as u
from astropy.coordinates import SkyCoord




Create a coordinate grid

Let's make a 3x3 grid first.

In [3]:
# We use units of angles

delta_angle = 2 # units in arcseconds

x_reference = 0 # units in arcseconds
y_reference = 0 # units in arcseconds

In [4]:
# Calculate start and End from reference point

end_x = x_reference + delta_angle
end_y = y_reference + delta_angle

In [11]:
# Number of points, we do the same for a square grid
# For 1 arcsecond resolution, we input the number of arcseconds in a degree

N = delta_angle+1 # * 60 * 60 # number of points is the number of arcseconds
N_points_x = N
N_points_y = N

In [12]:
# creating the axes with evenly spaced coordinate spots

vector_x = np.linspace (x_reference, end_x, N_points_x)
vector_y = np.linspace (y_reference, end_y, N_points_y)

In [13]:
# Use broadcasting to mimic the behaviour of a grid, without actually making a 2D Numpy Grid

In [14]:
N_tiles = N*N
print('The total number of tiles is ',N_tiles)

The total number of tiles is  9


In [15]:
vector_x

array([0., 1., 2.])

In [16]:
vector_y[:3]

array([0., 1., 2.])

Now, create ra and dec instances for each coordinates in the grid.
For that we use the np.tile and np.repeat methods.

In [17]:
tiled_vector_x = np.tile(vector_x,N_poinst_y)

In [18]:
tiled_vector_x

array([0., 1., 2., 0., 1., 2., 0., 1., 2.])

In [21]:
repeated_vector_y = np.repeat(vector_y,N_points_x)

In [22]:
repeated_vector_y

array([0., 0., 0., 1., 1., 1., 2., 2., 2.])

In [26]:
print('RA appears ',len(tiled_vector_x),' times and Dec also ',len(repeated_vector_y), '  . ')

RA appears  9  times and Dec also  9   . 


Pairwise matching them will create coordinate pairs
for each grid vertex (point).

Let's build the SkyCoord object now

In [27]:
# We need the RA and Dec values, and let's make them in arcseconds.

SkyCoord_RA_1D = np.copy(tiled_vector_x)*u.arcsec
SkyCoord_Dec_1D = np.copy(repeated_vector_y)*u.arcsec

In [28]:
# Now create the sky model, or the grid model
# I repeat the units to be clear!

sky_model = SkyCoord(ra=SkyCoord_RA_1D, dec = SkyCoord_Dec_1D, unit=u.deg)

In [ ]:
#